export const NAV_ITEMS = [
  { to: '/', label: 'Lista', icon: '🛒' },
  { to: '/stores', label: 'Butiker', icon: '🏪' },
  { to: '/history', label: 'Historik', icon: '📋' },
  { to: '/settings', label: 'Inställningar', icon: '⚙️' },
] as const

export const CATEGORIES = [
  'Frukt & Grönt',
  'Mejeri & Ägg',
  'Kött & Chark',
  'Fisk & Skaldjur',
  'Bröd',
  'Bageri & Fikabröd',
  'Fryst',
  'Skafferi',
  'Frukost',
  'Snacks & Godis',
  'Dryck',
  'Hygien',
  'Tvätt & Städ',
  'Papper & Hushåll',
  'Djurmat',
  'Barn & Familj',
  'Övrigt',
] as const

export const CATEGORY_COLORS: Record<string, string> = {
  'Frukt & Grönt':      'bg-green-100 text-green-800',
  'Mejeri & Ägg':       'bg-blue-100 text-blue-800',
  'Kött & Chark':       'bg-red-100 text-red-800',
  'Fisk & Skaldjur':    'bg-sky-100 text-sky-800',
  'Bröd':               'bg-amber-100 text-amber-800',
  'Bageri & Fikabröd':  'bg-yellow-100 text-yellow-800',
  'Fryst':              'bg-cyan-100 text-cyan-800',
  'Skafferi':           'bg-orange-100 text-orange-800',
  'Frukost':            'bg-rose-100 text-rose-800',
  'Snacks & Godis':     'bg-pink-100 text-pink-800',
  'Dryck':              'bg-purple-100 text-purple-800',
  'Hygien':             'bg-fuchsia-100 text-fuchsia-800',
  'Tvätt & Städ':       'bg-slate-100 text-slate-800',
  'Papper & Hushåll':   'bg-stone-100 text-stone-800',
  'Djurmat':            'bg-lime-100 text-lime-800',
  'Barn & Familj':      'bg-violet-100 text-violet-800',
  'Övrigt':             'bg-gray-100 text-gray-600',
}
